const AVANÇA = DOCUMENT.QUERSELECTORALL('.BTN-PROXIMO')

AVANÇA.FOREACH(BUTTON => {
    BUTTON.ADDEVENTLISTENER('CLICK', FUNCTION(){
        CONST ATUAL = DOCUMENT.QUERYSELECTOR('.ATIVO')
        CONST PROXIMOPASSO = 'PASSO-' + this.GETATRIBUTE('DATA-PROXIMO');

        ATUAL.CLASSLIST.REMOVE('ATIVO');
        DOCUMENT.GETELEMENTBYID(PROXIMOPASSO).CLASSLIST.ADD('ATIVO');
    })
})